### ISSUE TITLE
G2.10 Data Importer Importer + Validator API

### ISSUE THREAD

**Issue by reynoldtan** [TripalCultivate/TripalCultivate-Phenotypes#10]
Create importer + validator api for phenotypes collect and phenotypes share.

**Comment by laceysanderson** [comment]
This sounds like it should be multiple branch/PRs. We want to keep these as small as possible. For example, only the importer class outline for one of the modules with the form defined and routes to support should be a single PR.

Can you come up with a full design here in the issue including how you intend to break this up into reviewable chunks?

Some questions you may want to answer/think about:

- Are you still thinking phonocollect + phenoshare will share a form or did we manage to convince you in the office they should be two separate forms? 
- What sort of things do you want to validate? 
- Are you planning a multi-stage form like we had for analyzed phenotypes? 
- Are you supporting the same formats as before? 
- How do you see the raw phenotypes changing to support the new trait-method-unit approach?

**Comment by laceysanderson** [comment]
Closing in favour of smaller issues/PRs.
