### ISSUE TITLE
G4.110 Re-evaluate the parameters given to validateFile()

### ISSUE THREAD

**Issue by carolyncaron** [TripalCultivate/TripalCultivate-Phenotypes#110]
### Branch

g4.110-repairValidDataFile

### Groups

Group 4 - API | Services | Plugins

### Describe

I brought up during review of #98 that it was unclear which parameters given to validateFile() by the ValidDataFile validator were required or not, and whether the $fid parameter should be listed first as it is more important. Lacey clarified with me that we should only expect either $filename on its own or both parameters, since acquiring the fid of the file also means the developer has access to the filename before calling this function. See this comment thread on the PR for context:
<img width="836" alt="Screenshot 2024-09-27 at 2 19 54 PM" src="https://github.com/user-attachments/assets/3c9531fb-71c6-45ee-b40d-c419348b02f2">

However, I still have a few concerns that Lacey and I realized deserves its own issue, since it will involve changes in multiple places (for eg. `testValidDataFile`, `ValidatorInterface` and the validator itself). These concerns are:
- What should we do if the $fid and $filename are both provided, but they aren't of the same file? Shouldn't the developer be warned about this?
- Ideally, we would prevent a case where the developer might provide the $filename as an empty string and then the $fid, since they know that the method will happily accept it. This is how it would look when written: `validateFile('', $fid);`
- The current logic of the code assumes a file object managed by the Drupal File System, which begs the question why both parameters are even necessary. If we want to cater to situations where we aren't relying on the Drupal File System (for example: utilize a new drag-and-drop module, or use drush to call the method directly), then we'd have to change our current approach

### Design

See `validateFile()` in `trpcultivate_phenotypes/src/Plugin/Validators/validDataFile.php` for the current design.

**Comment by carolyncaron** [comment]
To follow up on this, when trying to use validateFile() in the Traits Importer, it turns out I don't have access to the filename in `$form_state->getValues()`. Therefore I have to leave the first parameter blank:

<img width="570" alt="Screenshot 2024-10-04 at 4 17 54 PM" src="https://github.com/user-attachments/assets/f619fc02-0334-46de-b58e-aeaa08cf9696">

**Comment by laceysanderson** [comment]
After discussion, the plan is:

- validateFile will only take one required parameter: fid
- some cases will go away since we don't need to validate that the filename and fid passed in are the same
- all cases remaining will keep the same failedItems (i.e. do not remove filename reporting since it is most useful for the user)
- the interface for validators will need to be updated as will associated tests.
- cases to be removed:
  - 'Filename is empty string'
  - 'The filename provided does not match the filename set in the file object.'
  - 'Filename failed to load a file object'
