### ISSUE TITLE
G0.06 Configuration Form for Ontology and Terms

### ISSUE THREAD

**Issue by reynoldtan** [TripalCultivate/TripalCultivate-Phenotypes#6]
This configuration will define vocabulary terms and controlled vocabulary terms used to house traits and by many processes in the phenotypes module.

![Ontology Terms - Terms](https://user-images.githubusercontent.com/15472253/232533132-3129c06c-9bbe-47b5-bbe5-dac1cea27d90.jpg)
![Ontology Terms](https://user-images.githubusercontent.com/15472253/232533208-c802d85b-94d8-4f08-bcba-373c3e9cc787.jpg)

**Comment by laceysanderson** [comment]
Merged
